include(${CMAKE_CURRENT_LIST_DIR}/common/BuildLocation.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/common/BuildType.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/common/TestCompiler.cmake)

checkForCxx17Compiler(CXX17_COMPILER)
if(CXX17_COMPILER)
    enableCxx17()
else()
    message(FATAL_ERROR "The C++17 standard not supported")
endif()
